#!/usr/bin/env python3
"""Write CRC test vectors for tb_crc8 into tb/vectors/.

crc8.hex is a stream of 8-bit hex tokens for $readmemh:

    count_lo count_hi                 number of messages, 16 bit little endian
    length  byte .. byte  crc         one message per line

crc8_size.svh holds the token and message counts as localparams, so the
testbench can size its array exactly. The first messages are fixed known
answers, the rest are random with a fixed seed, so the files only change
when this script does. Regenerate with `make vectors` from sim/.
"""

import pathlib
import random
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from crsf import CH_MAX, CH_MID, CH_MIN, crc8, rc_frame  # noqa: E402

VECTORS = pathlib.Path(__file__).resolve().parents[1] / "vectors"
OUT = VECTORS / "crc8.hex"
SIZE = VECTORS / "crc8_size.svh"    # array size for the testbench
COUNT = 1000
MAX_LEN = 62


def messages():
    yield b"123456789"                    # catalogue check value, 0xBC
    yield b""                             # nothing fed after clear, 0x00
    yield b"\x01"                         # the polynomial itself, 0xD5
    yield rc_frame([CH_MID] * 16)[2:-1]   # type + payload of real frames
    yield rc_frame([CH_MIN] * 16)[2:-1]
    yield rc_frame([CH_MAX] * 16)[2:-1]
    yield bytes(23)
    yield bytes([0xFF] * 23)
    rng = random.Random(0xC8)
    while True:
        n = rng.randint(1, MAX_LEN)
        yield bytes(rng.randrange(256) for _ in range(n))


def main():
    lines = [
        "// generated by tb/model/gen_vectors.py, do not edit by hand",
        "// count_lo count_hi, then per message: length, bytes, crc",
        f"{COUNT & 0xFF:02X} {COUNT >> 8:02X}",
    ]
    tokens = 2
    gen = messages()
    for _ in range(COUNT):
        m = next(gen)
        lines.append(" ".join(f"{b:02X}" for b in (len(m), *m, crc8(m))))
        tokens += len(m) + 2
    VECTORS.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    SIZE.write_text(
        "// generated by tb/model/gen_vectors.py together with crc8.hex\n"
        f"localparam int CRC8_VEC_TOKENS   = {tokens};\n"
        f"localparam int CRC8_VEC_MESSAGES = {COUNT};\n"
    )
    print(f"{OUT.name}: {COUNT} messages, {tokens} tokens; {SIZE.name} updated")


if __name__ == "__main__":
    main()
